### ISSUE TITLE
Error in example: "Create and commit a new transaction"

### ISSUE THREAD

**Issue by zekylaf** [seegno/bitreserve-sdk-php#100]
Hi, in Readme says getCardsById('ade869d8-7913-4f67-bb4d-72719f0a2be0'); but I think that it would say getCardById('ade869d8-7913-4f67-bb4d-72719f0a2be0'); (no s in getCardById).

It would be useful to add the possibility to get a card using its address too.

**Comment by nunorafaelrocha** [comment]
Hi @zekylaf, Well spotted, I've created a pull request #101 to fix that typo. 

About that `getCardByAddress`, I've created a new issue #102 to discuss this issue.
