### ISSUE TITLE
Add getter for currencies to the User model

### ISSUE THREAD

**Issue by nunofgs** [seegno/bitreserve-sdk-php#76]
The currencies array on the user determines which currencies can be used to create cards. It would be nice to have this array exposed on the User model.

**Comment by nunorafaelrocha** [comment]
This array is already exposed on the `BitreserveClient`, and I don't think is something that should belong to the user model.

User model should be only for operations related to the user, like getting the cards, transactions, personal information, etc...

I think available currencies is like a "system property" that should be requested to the main class, `BitreserveClient`.

What are your thoughts about this?

**Comment by nunofgs** [comment]
The `BitreserveClient` exposes a currencies array but it's entirely different from the User's currencies. For example: some users might only have access to a subset of the public currencies, or, they could have access to currencies that are not public.

**Comment by nunorafaelrocha** [comment]
Oh, right, sorry. Actually I really need to update the user model as soon as possible! :smile:
